name: Build Study Vault Hub Desktop Apps

on:
  workflow_dispatch:
  push:
    tags:
      - "desktop-v*"

jobs:
  windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
           node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Build Windows installer
        run: npm run electron:build:win

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: Study-Vault-Hub-Windows
          path: |
            dist/**/*.exe
            release/**/*.exe
            out/**/*.exe
          if-no-files-found: error


  macos:
    name: Build macOS DMG
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Build macOS installer
        run: npm run electron:build:mac

      - name: Upload macOS installer
        uses: actions/upload-artifact@v4
        with:
          name: Study-Vault-Hub-macOS
          path: |
            dist/**/*.dmg
            release/**/*.dmg
            out/**/*.dmg
          if-no-files-found: error
